# -*- coding: utf-8 -*-
"""Remote Upload Google Drive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zGYd7-OSZs8_I_QN7bzuZDKd_-6qoNY
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Take remote URL as input
remote_url = input("Enter the URL of the file you want to download: ")

# Download the file to Google Drive
!wget -P /content/drive/MyDrive/Backup/ {remote_url}

# Perform a loop (if needed)
from tqdm import tqdm

# Provide a meaningful description for the loop
for i in tqdm(range(100), desc="Iterating over range"):
    # Your code here
    pass